# Generated by Django 3.2.7 on 2022-01-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Roll_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=255)),
                ('Mobile', models.IntegerField(max_length=11)),
                ('School', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Students_Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField(max_length=5)),
                ('Physics', models.IntegerField(max_length=5)),
                ('Chemistry', models.IntegerField(max_length=5)),
                ('Biology', models.IntegerField(max_length=5)),
                ('English', models.IntegerField(max_length=5)),
                ('Students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.students')),
            ],
            options={
                'db_table': 'Students_Academics',
            },
        ),
    ]
