# Generated by Django 3.2.7 on 2022-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_alter_students_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Mobile',
            field=models.IntegerField(max_length=20),
        ),
    ]
