# Generated by Django 3.2.7 on 2022-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_alter_students_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Mobile',
            field=models.CharField(max_length=12),
        ),
    ]
